pkg/instance/start.go: fix lint error on windows
```
Error: pkg\instance\start.go:274:65: SA4023: this comparison is always true (staticcheck)
  		if err := syscall.Exec(limactl, haCmd.Args, haCmd.Environ()); err != nil {
```

Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
(cherry picked from commit bdf7c7f3d7004a7cd8f0698f0eca67558859bde2)
> Conflicts:
>	pkg/instance/start.go
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>