templates: skip Arch Linux 20240815.255016
20240815.255016 does not work due to "No space left on device".
Caused by canonical/cloud-init issue 5614.

```
2024-08-16 16:15:27,738 - util.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.12/site-packages/cloudinit/config/cc_resizefs.py'>) failed
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/cloudinit/config/modules.py", line 270, in _run_modules
    ran, _r = cc.run(
              ^^^^^^^
  File "/usr/lib/python3.12/site-packages/cloudinit/cloud.py", line 71, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/cloudinit/helpers.py", line 156, in run
    results = functor(**args)
              ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/cloudinit/config/cc_resizefs.py", line 327, in handle
    resize_cmd = resizer(resize_what, devpth)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/cloudinit/config/cc_resizefs.py", line 81, in _resize_btrfs
    system_btrfs_ver = util.Version.from_str(
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/cloudinit/util.py", line 3145, in from_str
    return cls(*(list(map(int, version.split(".")))))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10\n-EXPERIMENTAL -INJECT -STATIC +LZO +ZSTD +UDEV +FSVERITY +ZONED CRYPTO=libgcrypt'
```

Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>